### ISSUE TITLE
Rewinding using the scrubber doesn't remove overlays

### ISSUE THREAD

**Issue by graywithanA** [brightcove/videojs-overlay#10]
This is similar, or potentially the same, as issue #8.  When scrubbing backwards any overlays that display based on time and should no longer display do not seem to be removed.  Furthermore, if you scrub backwards, but still within the range of time the current overlay is displayed, a second instance of the overlay is created.  This causes the appearance of any opacity settings to be cut in half each time.

For example, say I have an overlay that should display from 0-10 seconds and another from 10-20 seconds.  If I let the video play to 15 seconds and then...

...click back to 12 seconds: a second overlay of the same content is added.
...click the playhead and drag back to 12 seconds: many overlays are added.
...click back to 5 seconds: both the 0-10 and 10-20 overlays are displayed over top of each other.

I created this as a separate issue because @kevinmann suggested his problem arose when clicking the scrubber multiple times whereas the issue I'm describing doesn't require multiple clicks of the scrubber.  The problem occurs whether you scrub backwards by clicking once at a point behind the playhead or if you drag the playhead backwards.

**Comment by creeptonik** [comment]
Hey gray, is there any update on this issue?

**Comment by graywithanA** [comment]
I implemented a solution that works for my particular application but likely wouldn't work in all scenarios.  For instance I'm not using events to show/hide the overlays.  I laid out a work around [here] (https://github.com/brightcove/videojs-overlay/issues/8#issuecomment-63577867) although I have since updated it to be a bit more reliable and a bit less specific to my situation.  I'll try to get a forked copy of the project up with my solution for those that are interested.  I'm a bit busy right now with some deadlines but I'll do my best.

**Comment by creeptonik** [comment]
Thanks for that, I'll give it a go and feedback

**Comment by Kreozot** [comment]
Possibly fixed by my PR: #14.

**Comment by misteroneill** [comment]
This should be supported now. Apologies for the lack of responsiveness here!
