### ISSUE TITLE
Overlay appears behind video

### ISSUE THREAD

**Issue by saiena** [brightcove/videojs-overlay#108]
Everything seems to be working, but the overlay appears behind the video (see attached screenshot).

I get the same results with  both our deployed VideoJS (version 6.9.0) and with the latest release (7.5.5).

Tested with latest Chrome and Safari on Mac OS.

I tried increasing z-index of the overlay div (i.e., the div with class: vjs-overlay vjs-overlay-right vjs-overlay-background), but saw no difference.

Please advise.

![screenshot](https://user-images.githubusercontent.com/458602/59460195-5bd7dc80-8dd3-11e9-8a65-d955666e4250.png)

**Comment by saiena** [comment]
Solution found.

I saw no mention in the documentation of the need to include the css file (videojs-overlay.css) for the overlay plugin.

Including it solves the problem.

**Comment by TDDR** [comment]
Hello,

I know this is a bit of a long shot but I was wondering if someone could help me with implementing videojs-overlay? 

I am working on [an issue](https://github.com/FreeTubeApp/FreeTube/issues/694) for FreeTube and am having troubles getting the overlay out of the background. I know it's there but like with this issue, it's stuck in the background. I have imported the css file as suggested here with no luck.

Any help is greatly appreciated.
