### ISSUE TITLE
Does this plugin work with Google Vast tags?

### ISSUE THREAD

**Issue by kcwoodfield** [brightcove/videojs-overlay#13]
I'm curious if anyone has implemented a solution for Google's ads instead of basic html.  

The plugin looks like it accepts either a string or object.

**Comment by dmlap** [comment]
Overlay ads are a bit more complicated than the problems this plugin is trying to solve. I'd recommend checking out one of the video.js ad plugins ([videojs-ima](https://github.com/googleads/videojs-ima) for instance).
