### ISSUE TITLE
Example.html isn't displaying an overlay for me

### ISSUE THREAD

**Issue by karifreu** [brightcove/videojs-overlay#15]
I downloaded the files and put the entire folder, including the example.html file up on my web server, but the overlay never shows on the video on that sample page. I also played the example.html file straight from my hard drive in the folder it came in and also no overlay. I am trying to show a transparent hyperlinked image on top of a video so that the user can click the video at any time to learn more about the product featured in it. I tried this plugin and the videojs-imageOverlay, but I can't seem to get either of them to work. I'm hoping this is just a basic user error, but I can't figure out what it could be. This may not be the right forum for this, but I am having an "issue" with this plugin so I hope I'm not off base for posting here. Any help would be much appreciated. Thanks!

**Comment by Kreozot** [comment]
Are you sure that "video.js" library itself is working properly?
Did you run "npm install" after download the files? Because "video.js" comes from npm in the example (```<script src="node_modules/video.js/dist/video-js/video.js"></script>```)

**Comment by Kreozot** [comment]
Or if you don't have npm you can simply replace links to video.js to this:
```html
<link href="//vjs.zencdn.net/4.12/video-js.css" rel="stylesheet">
<script src="//vjs.zencdn.net/4.12/video.js"></script>
```

**Comment by karifreu** [comment]
What about the links to the videojs-overlay.js file? Is it okay to have that on the server without running any installation? Like this: <script src="lib/videojs-overlay.js"></script>

This will probably be easier if I share my code so here’s the page I’m working on:

http<http://stmedia.com/files/web/bpic/testing/video-kf-6.html><ftp://stmedia.com//files/web/bpic/testing/video-kf-6.html>://stmedia.com/files/web/bpic/testing/video-kf-6.html<http://stmedia.com/files/web/bpic/testing/video-kf-6.html>


--

Kari Freudenberger
Director of Online Media
ST Media Group International
11262 Cornell Park Drive
Cincinnati, OH 45242
(513) 263-9374
kari.freudenberger@stmediagroup.com

**Comment by Kreozot** [comment]
Your HTML is not valid. Delete this part:
```html
 data-setup="{"example_option":true}"
```

**Comment by Kreozot** [comment]
In future use single quotes in tag attribute if there is double quotes inside it:
```html
data-setup='{ "controls": true, "autoplay": false, "preload": "auto" }'
```

**Comment by karifreu** [comment]
Thanks! After some head scratching and creative coding, I got it to work. See here:
http://stmedia.com/files/web/bpic/testing/videojs-overlay-master/video-kf-9.html

--

Kari Freudenberger
Director of Online Media
ST Media Group International
11262 Cornell Park Drive
Cincinnati, OH 45242
(513) 263-9374
kari.freudenberger@stmediagroup.com
