### ISSUE TITLE
clickable images in overlay

### ISSUE THREAD

**Issue by gine** [brightcove/videojs-overlay#19]
I'm trying to display few image buttons on the overlay, Someting like this:
`
var content = '<a title="'+info.title+'" class="bcVoteBar" onclick="'+action+'">'
	'<img class="bcVoteBar" src="'+info.img+'">'
'</a>';
`
but the `<img> tag is stripped away. Is possible to implement what i need with your overlay plugin? if no, can you implement that feature?

**Comment by misteroneill** [comment]
@gine Can you clarify what you mean by "the ` tag is stripped away"?

**Comment by gine** [comment]
This part of the content is removed: 
`<img class="bcVoteBar" src="'+info.img+'">`

**Comment by misteroneill** [comment]
Sorry for the delayed response, but it looks like you're missing some `+`es between the 3 strings you have here. I just verified that it's definitely possible to put images into an overlay.

**Comment by gine** [comment]
@misteroneill 
i realized it whit another components. but yes, it appears that is a simple js error. hand on my face!

**Comment by bhartendukumar12** [comment]
can we overlay map in the player and integrate the map with the video.
check the link      https://www.youtube.com/watch?v=uscu96N254o
