### ISSUE TITLE
Can't use non-Integer value for start

### ISSUE THREAD

**Issue by mboles** [brightcove/videojs-overlay#22]
When the start is non-Integer get an error: **Uncaught Error: invalid "start" option; expected number or string**

Of course, I can use Math.floor(), but maybe best just to put that in the plugin?  I am using the duration in a calculation, which seems like valid use case.  Also, using a non-Integer value worked in earlier versions of the plugin.

**Comment by misteroneill** [comment]
Thanks for the report, Matt! :+1: Will get this fixed today.
