### ISSUE TITLE
HLS ?

### ISSUE THREAD

**Issue by HankBrown** [brightcove/videojs-overlay#28]
Not having success using this with https://github.com/videojs/videojs-contrib-hls/tree/master/docs

That page says "Your plugin won't work with videos that don't use videojs-contrib-hls and the best plugins work across all the media types that video.js supports."

Does videojs-overlay use videojs-contrib-hls? How would I know?!

**Comment by gkatsev** [comment]
videojs-overlay doesn't use contrib-hls. The part that says "your plugin won't work with videos that don't use contrib-hls..." specifically refers to the code snippet above it and is just about usage in contrib hls: https://github.com/videojs/videojs-contrib-hls/blob/2cce0c1859a53fee5c6ed46deb79cfc550cead45/README.md#runtime-properties
videojs-overlay can work with contrib-hls and it can work if you're not using it as well.
