### ISSUE TITLE
JSX support as content

### ISSUE THREAD

**Issue by williammustaffa** [brightcove/videojs-overlay#35]
I'm trying to use this with react. Can it support JSX on the content option?

**Comment by gkatsev** [comment]
JSX is a compile-to-js language. I don't think we could support it without adding that kind of requirement and it is not something that we'd want to add.
You can already give videojs-overlay an [element reference](https://github.com/brightcove/videojs-overlay#content) directly to use, so, if you use JSX yourself, you could do that.
I don't think it makes sense for videojs-overlay to support JSX directly.
