### ISSUE TITLE
Overlay not working with Ipad on full screen mode

### ISSUE THREAD

**Issue by abureviewer1** [brightcove/videojs-overlay#54]
Hi,
While I check your plugin it work perfect on Firefox, chrome but when I check with Safari browser it does not show the text on full screen mode can you help me I need this.

**Comment by Ricalsin** [comment]
I have this same problem on these two devices I was able to test:

ipad 8.55, version 11.3, model ME999LL/A
iphone 7 version 11.3.1 Model:MKT12LL/A

Works great on all desktop browsers, android devices and even the two devices above - except when it's in fullscreen mode.

**Comment by gkatsev** [comment]
When you go fullscreen on iOS, it enters a native playback mode. In that mode it is not possible to display HTML elements on top of the video. Unfortunately, this is a platform limitation.
