### ISSUE TITLE
Double add overlays.

### ISSUE THREAD

**Issue by kevinmann** [brightcove/videojs-overlay#8]
In my testing I have something like:

```
player.overlay({
  overlays: [{
    content: "Test1",
    start: 0,
    end: 15,
    align: 'bottom'
   }, 
   {
    content: "Test2",
    start: 17,
    end: 30,
    align: 'bottom'
  }]
});
```

If I click more than once on the scrubber at around 12 seconds for example,  I get multiple overlays displayed. Which then do not remove after the end trigger.

**Comment by misteroneill** [comment]
It looks like this ancient issue is still an... issue. I'll make sure it gets addressed in #21.

**Comment by mehmoodmemon** [comment]
I faced same issue i did it manually in two steps first by checking other overlays time and then checking the overlay object already exist on screen or not.

**Step1:** Add this block of code after **hideOverlay** function


     hideOtherOverlays = function(player, settings, currentOverlay){
	  if(currentOverlay && settings.overlays){
		for (var i=0; i<settings.overlays.length; i++) {
		  var overlay = settings.overlays[i];
		  if(overlay != currentOverlay){
			  if(overlay.start && overlay.start>currentOverlay.start){
				  hideOverlay(player,settings,overlay);
			  }
			  if(overlay.end && overlay.end<=currentOverlay.end){
				  hideOverlay(player,settings,overlay);
			  }
		    }
		 }
        }
    }

**Step2:** Update **showOverlay** with this.

 	  showOverlay = function(player, settings, overlay) {
		// create the overlay wrapper
		var el = document.createElement('div'),
			content = overlay.content || settings.content,
			align = settings.align || overlay.align,
			customClass = settings.class || overlay.class;
		
		el.className = 'vjs-overlay';	
		
		var customeClassName = 'customOverlay_'+overlay.start+'_'+overlay.end+'_';
		
		hideOtherOverlays(player,settings,overlay);
		
		if(document.getElementsByClassName(customeClassName).length==0)
		{
			overlay.el = el;

			// if an alignment was specified, add the appropriate class
			if (align) {
			  el.className += ' vjs-overlay-' + align;
			}

			if (customClass) {
			  el.className += ' ' + customClass;
			}
			el.className += ' ' + customeClassName;
			
			// append the content
			if (typeof content === 'string') {
			  el.innerHTML = content;
			} else {
			  el.appendChild(content);
			}

			// add the overlay to the player
			player.el().appendChild(el);
		}
		
	  };

This works for me. But still in search for better solution.

**Comment by misteroneill** [comment]
I have engaged in a major refactor of this plugin as part of #21 that should address this issue. It should be merged and released this week - I will post here (and close the issue) when it's fixed!
